VSCodium (1.84.2, undefined, desktop)
Jupyter Extension Version: 2023.9.100.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder ~/Documents/calculus_add, Home = /home/like
17:48:46.082 [info] Telemetry level is off
17:48:46.082 [info] Experiments are disabled, only manually opted experiments are active.
17:48:46.285 [info] Start refreshing Kernel Picker (1701618526285)
17:48:46.287 [info] Using Pylance
17:48:46.378 [warn] Failed to get activated env vars for /bin/python in 68ms
17:48:46.389 [info] Process Execution: /bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
17:48:46.410 [info] Process Execution: /bin/python -m pip list
17:48:47.314 [info] End refreshing Kernel Picker (1701618526285)
18:05:22.665 [info] Handle Execution of Cells 3 for ~/Documents/calculus_add/extra_xor.ipynb
18:05:22.668 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher  (Python Path: /bin/python, Unknown, 3.11.6) for '~/Documents/calculus_add/extra_xor.ipynb' (disableUI=false)
18:05:22.694 [warn] Failed to get activated env vars for /bin/python in 22ms
18:05:22.703 [info] Process Execution: /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
18:05:22.712 [info] Process Execution: /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"bb580e59-076a-4c35-bd8a-1cb2a1c405d8" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-2728277057zmXyS6Q1.json
    > cwd: ~/Documents/calculus_add
18:05:22.715 [warn] Failed to get activated env vars for /bin/python in 34ms
18:05:22.722 [info] Process Execution: /bin/python -m pip list
18:05:22.855 [info] ipykernel version & path 6.27.1, /usr/lib/python3.11/site-packages/ipykernel/__init__.py for /bin/python
18:05:23.047 [warn] StdErr from Kernel Process [IPKernelApp] WARNING | debugpy_stream undefined, debugging will not be enabled
18:05:23.139 [info] Started Kernel Python 3.11.6 (pid: 283379)
18:05:23.139 [info] Started new session fbee1627-6cbd-4f94-ac86-295d92b78e91
18:05:23.174 [info] Process Execution: /bin/python ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.9.100-universal/pythonFiles/printJupyterDataDir.py
18:05:23.180 [info] Kernel acknowledged execution of cell 3 @ 1701619523180
18:05:23.237 [info] End cell 3 execution @ 1701619523237, started @ 1701619523180, elapsed time = 0.057s
18:05:26.794 [info] Handle Execution of Cells 3 for ~/Documents/calculus_add/extra_xor.ipynb
18:05:26.799 [info] Kernel acknowledged execution of cell 3 @ 1701619526799
18:05:26.800 [info] End cell 3 execution @ 1701619526800, started @ 1701619526799, elapsed time = 0.001s
18:05:33.350 [info] Handle Execution of Cells 5 for ~/Documents/calculus_add/extra_xor.ipynb
18:05:33.354 [info] Kernel acknowledged execution of cell 5 @ 1701619533354
18:05:33.355 [info] End cell 5 execution @ 1701619533355, started @ 1701619533354, elapsed time = 0.001s
22:55:19.956 [info] Disposing HostJupyterExecution
22:55:19.956 [info] Shutting down notebooks for 574f0cdf-e38b-4078-b949-5efe82f92db9
22:55:19.957 [info] Dispose Kernel '~/Documents/calculus_add/extra_xor.ipynb' associated with '~/Documents/calculus_add/extra_xor.ipynb'
22:55:19.957 [info] Dispose Kernel process 283379.
22:55:19.965 [info] Disposing HostJupyterExecution
22:55:19.976 [warn] Failed to delete connection file file://~/.local/share/jupyter/runtime/kernel-v2-2728277057zmXyS6Q1.json for pid 283379 [Canceled (FileSystemError): Canceled
	at S._handleError (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:34220)
	at Object.stat (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30375)
	at async fp.delete (~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:17:19371)
	at async ~/.vscode-oss/extensions/ms-toolsai.jupyter-2023.9.100-universal/out/extension.node.js:24:88616] {
  code: 'Unknown'
}
